version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sekolah-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sdnb1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - sekolah-network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sekolah-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sdnb1
      - DB_USERNAME=root
      - DB_PASSWORD=
      - CLOUDINARY_KEY=682949258755478
      - CLOUDINARY_SECRET=2cBeuesCFW2-q6tRpy0ZmQx9ptw
      - CLOUDINARY_CLOUD_NAME=dbt7elx0d
      - CLOUDINARY_URL=cloudinary://682949258755478:2cBeuesCFW2-q6tRpy0ZmQx9ptw@dbt7elx0d
      - CLOUDINARY_PREFIX=sdnb1
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sekolah-network

networks:
  sekolah-network:
    driver: bridge

volumes:
  mysql_data:
  sekolah-data: